[package]
name = "fastly-compute-at-edge-template"
publish = false
version = "0.1.0"
edition = "2021"
rust-version = "1.59"

[profile]
    [profile.release]
    debug = 1

[dependencies]
fastly = "^0.8.2"
