# https://prettier.io/docs/en/configuration.html

arrowParens = "always"
bracketSpacing = true
endOfLine = 'lf'
printWidth = 120
semi = true
singleAttributePerLine = true
singleQuote = true
tabWidth = 4
trailingComma = "es5"
useTabs = false
