on:
    workflow_call:

# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
    # We need to limit the workflow concurrency to ensure a deployment order as FIFO.
    #
    # If we use `${{ github.workflow }}-${{ github.ref }}` and the invoked workflow for our `ci` job also has same group id,
    # this workflow will be cancelled by the invoked workflow's `concurrency` setting.
    # To avoid this problem, we use uuid v4 as a key to mark this workflow's uniqueness.
    group: "f8b37ebf-5018-4559-a165-64df63235991"

# https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
# https://docs.github.com/en/actions/learn-github-actions/contexts
jobs:
    deploy_for_canary:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                release_channel: ["canary"]
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/download_build_artifacts
              with:
                  git-sha: ${{ github.sha }}
                  release-channel: ${{ matrix.release_channel }}
                  build-type: release
            # TODO(#7)
