name: CI on main branch

on:
    push:
        branches:
            - "main"

# see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
    # If we use `${{ github.workflow }}-${{ github.ref }}` and the invoked workflow for our `ci` job also has same group id,
    # this workflow will be cancelled by the invoked workflow's `concurrency` setting.
    # To avoid this problem, we use uuid v4 as a key to mark this workflow's uniqueness.
    group: "63f09107-e884-4366-b912-66ec06064c00"
    cancel-in-progress: true

jobs:
    ci:
        uses: ./.github/workflows/ci.yaml

    deploy:
        needs: [ci]
        runs-on: ubuntu-latest
        strategy:
            matrix:
                release_channel: ["canary"]
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/download_build_artifacts
              with:
                  git-sha: ${{ github.sha }}
                  release-channel: ${{ matrix.release_channel }}
                  build-type: release
            # TODO(#7)
