name: CI on main branch

on:
    push:
        branches:
            - "main"

# We don't limit this workflow concurrency to improve a thoughput for CI job that does not have to keep the order of job.
# Ideally we would like to use `jobs.<job_id>.concurrency` instead of specifying a concurrency group
# for each of workflows.
# But `jobs.<job_id>.concurrency` does not have order guarantee. We need to use this workaround.
#
#   > Note: When concurrency is specified at the job level, order is not guaranteed for jobs or runs that queue within 5 minutes of each other.
#   > https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idconcurrency

jobs:
    ci:
        uses: ./.github/workflows/__ci.yaml

    deploy:
        needs: [ci]
        uses: ./.github/workflows/__deploy_for_canary.yaml
