name: CI on main branch

on:
    push:
        branches:
            - "main"
    pull_request:

jobs:
    ci:
        uses: ./.github/workflows/ci.yaml

    expriment:
        uses: ./.github/workflows/experiment.yaml

    deploy:
        needs: [ci]
        runs-on: ubuntu-latest
        strategy:
            matrix:
                release_channel: ["canary"]
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/download_build_artifacts
              with:
                  git-sha: ${{ github.sha }}
                  release-channel: ${{ matrix.release_channel }}
                  build-type: release
            # TODO(#7)
